=== codie-arun/Training/Rmi/bill.dtd
<!ELEMENT bill (customername,billno,billdate,items+,total)>
<!ELEMENT items (item+)>
<!ELEMENT item (slno,itemname,unit,price,qty,amount)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT billno (#PCDATA)>
<!ELEMENT billdate (#PCDATA)>
<!ELEMENT slno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== codie-arun/Training/Rmi/bill.xml
<!DOCTYPE bill SYSTEM "bill.dtd">

<bill>
	<customername>Arun</customername>
	<billno>100</billno>
	<billdate>08-03-2021</billdate>
	<items>
		<item>
			<slno>1</slno>
			<itemname>Daal</itemname>
			<unit>1</unit>
			<price>120</price>
			<qty>5</qty>
			<amount>600</amount>
		</item>
	
		<item>
			<slno>2</slno>
			<itemname>Rice</itemname>
			<unit>1</unit>
			<price>60</price>
			<qty>5</qty>
			<amount>300</amount>
		</item>
	</items>
	<total>2500</total>
</bill>

=== codie-arun/Training/Rmi/newbill.xml
<!DOCTYPE bill SYSTEM "bill.dtd"><bill><customername>Arun</customername><billno>1000</billno><billdate>2021-03-20</billdate><items><item><slno>4</slno><itemname>milk</itemname><unit>1</unit><price>35</price><qty>6</qty><amount>210</amount></item><item><slno>4</slno><itemname>milk</itemname><unit>1</unit><price>35</price><qty>3</qty><amount>105</amount></item><item><slno>4</slno><itemname>milk</itemname><unit>1</unit><price>35</price><qty>4</qty><amount>140</amount></item><item><slno>3</slno><itemname>Paneer</itemname><unit>1</unit><price>100</price><qty>1</qty><amount>100</amount></item><item><slno>2</slno><itemname>Chicken</itemname><unit>1</unit><price>150</price><qty>65</qty><amount>9750</amount></item><item><slno>4</slno><itemname>milk</itemname><unit>1</unit><price>35</price><qty>10</qty><amount>350</amount></item><item><slno>2</slno><itemname>Chicken</itemname><unit>1</unit><price>150</price><qty>2</qty><amount>300</amount></item></items><total>10955</total></bill>
